# Cloudboz - Gitea Install
- name: "Install gitea"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ gitea_docker_name }}"
    image: "{{ gitea_docker_image }}:{{ gitea_docker_tag }}"
    networks:
      - name: cloudboz-network
    restart_policy: always
    env:
      USER_UID: "1000"
      USER_GID: "1000"
    volumes:
      - "/cloudboz/{{ gitea_docker_name }}-data/data:/data"
      - "/cloudboz/{{ gitea_docker_name }}-data/timezone:/etc/timezone:ro"
      - "/cloudboz/{{ gitea_docker_name }}-data/localtime:/etc/localtime:ro"
    ports:
      - "{{ gitea_docker_ports_app }}:3000"
      - "{{ gitea_docker_ports_ssh }}:22"
  tags:
    - install-gitea

# Cloudboz - Gitea Uninstall    
- name: "Uninstall gitea"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ gitea_docker_name }}"
    state: absent
  tags:
    - uninstall-gitea

# CloudBoz - Gitea Uninstall with Data
- name: "uninstall gitea data"
  become_user: "{{ ansible_user }}"
  shell: "sudo rm -fr /cloudboz/{{ gitea_docker_name }}-data"
  tags:
    - uninstall-gitea-data