# CloudBoz - swarm Install
- name: "Install swarm Container"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ swarm_docker_name }}"
    image: "{{ swarm_docker_image }}:{{ swarm_docker_tag }}"
    networks:
      - name: cloudboz-network
    restart_policy: always
    ports:
      - "{{ swarm_docker_ports }}:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/{{ ansible_user }}/{{ swarm_docker_name }}-data:/data"
  tags:
    - install-swarm

# CloudBoz - swarm Firewall Install
- name: "'{{ ufw_rule }}' port '{{ swarm_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ swarm_docker_ports | quote }}"
  tags:
    - install-swarm

# CloudBoz - swarm Uninstall
- name: "Remove swarm Container"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ swarm_docker_name }}"
    state: absent
  tags:
    - uninstall-swarm

# CloudBoz - swarm Firewall Uninstall
- name: "'{{ ufw_rule }}' port '{{ swarm_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
    delete: yes
  loop:
    - "{{ swarm_docker_ports | quote }}"
  tags:
    - uninstall-swarm