---
# CloudBoz - RabbitMQ Install
- name: "install rabbitmq"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ rabbitmq_docker_name }}"
    image: "{{ rabbitmq_docker_image }}:{{ rabbitmq_docker_tag }}"
    volumes:
      - "/cloudboz/{{ rabbitmq_docker_name }}-data:/var/lib/rabbitmq:rw"
    restart_policy: always
    networks:
      - name: cloudboz-network
    ports:
      - "{{ rabbitmq_docker_ui_ports }}:15672" # HTTP management UI
      - "{{ rabbitmq_docker_amqp_ports }}:5672" # AMQP protocol port
    privileged: true
    env:
      RABBITMQ_DEFAULT_USER: "{{ rabbitmq_docker_env_user }}"
      RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_docker_env_password }}"
  tags:
    - install-rabbitmq

# CloudBoz - RabbitMQ Firewall Install
- name: "'{{ ufw_rule }}' port '{{ rabbitmq_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ rabbitmq_docker_ui_ports | quote }}"
    - "{{ rabbitmq_docker_amqp_ports | quote }}"
  tags:
    - install-rabbitmq

# CloudBoz - RabbitMQ Uninstall    
- name: "Remove Rabbitmq Container"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ rabbitmq_docker_name }}"
    state: absent
  tags:
    - uninstall-rabbitmq

# CloudBoz - RabbitMQ Firewall Uninstall
- name: "'{{ ufw_rule }}' port '{{ rabbitmq_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
    delete: yes
  loop:
    - "{{ rabbitmq_docker_ui_ports | quote }}"
    - "{{ rabbitmq_docker_amqp_ports | quote }}"
  tags:
    - uninstall-rabbitmq

# CloudBoz - RabbitMQ Uninstall with Data
- name: "uninstall rabbitmq data"
  become_user: "{{ ansible_user }}"
  shell: "sudo rm -fr /cloudboz/{{ rabbitmq_docker_name }}-data"
  tags:
    - uninstall-rabbitmq-data