# CloudBoz - Rancher Install
- name: "install rancher"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ rancher_docker_name }}"
    image: "{{ rancher_docker_image }}:{{ rancher_docker_tag }}"
    networks:
      - name: cloudboz-network
    volumes:
      - "/cloudboz/{{ rancher_docker_name }}-data:/var/lib/rancher"
    restart_policy: always
    ports:
      - "{{ rancher_docker_ports_http }}:80"
      - "{{ rancher_docker_ports_https }}:443"
    privileged: true
  tags:
    - install-rancher

# CloudBoz - Rancher Uninstall
- name: "uninstall rancher"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ rancher_docker_name }}"
    state: absent
  tags:
    - uninstall-rancher

# CloudBoz - Rancher Uninstall Data
- name: "uninstall rancher data"
  become_user: "{{ ansible_user }}"
  shell: "sudo rm -fr /cloudboz/{{ rancher_docker_name }}-data"
  tags:
    - uninstall-rancher-data