- hosts: all
  become: true
  gather_facts: yes
  vars_files:
    # ------------- #
    # CLOUDBOZ INIT #
    # ------------- # 

    - group_vars/cloudboz/cloudboz.yml
    # - group_vars/cloudbozvault/dns.vault
    # - group_vars/cloudbozvault/ssl.vault

    # -------------------- #
    # CLOUDBOZ MARKETPLACE #
    # -------------------- #

    # CI/CD
    - group_vars/marketplace/cicd/jenkins.yml
    - group_vars/marketplace/cicd/gitlabrunner.yml

    # CMS
    - group_vars/marketplace/cms/wordpress.yml
    - group_vars/marketplace/cms/joomla.yml

    # DATA STREAM
    - group_vars/marketplace/datastream/kafka.yml
    - group_vars/marketplace/datastream/rabbitmq.yml

    # DATABASE NOSQL
    - group_vars/marketplace/dbnosql/mongodb.yml
    - group_vars/marketplace/dbnosql/mongodbexpress.yml
    - group_vars/marketplace/dbnosql/redis.yml
    - group_vars/marketplace/dbnosql/rediscommander.yml

    # DATABASE SQL
    - group_vars/marketplace/dbsql/mysql.yml
    - group_vars/marketplace/dbsql/mysqladmin.yml
    - group_vars/marketplace/dbsql/postgres.yml
    - group_vars/marketplace/dbsql/postgresadmin.yml

    # GIT
    - group_vars/marketplace/git/gitlab.yml
    - group_vars/marketplace/git/gitea.yml

    # CONTAINER ORCHESTRATION
    - group_vars/marketplace/orchestration/swarm.yml
    - group_vars/marketplace/orchestration/kubernetes.yml

    # ORCHESTRATION MANAGER
    - group_vars/marketplace/orchestrationmanager/portainer.yml
    - group_vars/marketplace/orchestrationmanager/rancher.yml

    # STORAGE
    - group_vars/marketplace/storage/minio.yml
    - group_vars/marketplace/storage/owncloud.yml

  roles:
    # ------------- #
    # CLOUDBOZ INIT #
    # ------------- # 

    - cloudboz/commons
    - cloudboz/optimization
    - cloudboz/network

    # -------------------- #
    # CLOUDBOZ MARKETPLACE #
    # -------------------- #

    # CI/CD
    - marketplace/cicd/jenkins
    - marketplace/cicd/gitlabrunner

    # CMS
    - marketplace/cms/wordpress
    - marketplace/cms/joomla

    # DATA STREAM
    - marketplace/datastream/kafka
    - marketplace/datastream/rabbitmq

    # DATABASE NOSQL
    - marketplace/dbnosql/mongodb
    - marketplace/dbnosql/mongodbexpress
    - marketplace/dbnosql/redis
    - marketplace/dbnosql/rediscommander

    # DATABASE SQL
    - marketplace/dbsql/mysql
    - marketplace/dbsql/mysqladmin
    - marketplace/dbsql/postgres
    - marketplace/dbsql/postgresadmin

    # GIT
    - marketplace/git/gitlab
    - marketplace/git/gitea

    # CONTAINER ORCHESTRATION
    - marketplace/orchestration/swarm
    - marketplace/orchestration/kubernetes

    # ORCHESTRATION MANAGER
    - marketplace/orchestrationmanager/portainer
    - marketplace/orchestrationmanager/rancher

    # STORAGE
    - marketplace/storage/minio
    - marketplace/storage/owncloud