# CloudBoz - owncloud Install
- name: "install owncloud"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ owncloud_docker_name }}"
    image: "{{ owncloud_docker_image }}:{{ owncloud_docker_tag }}"
    networks:
      - name: cloudboz-network
    volumes:
      - "/cloudboz/{{ owncloud_docker_name }}-data:/var/lib/owncloud"
    restart_policy: always
    ports:
      - "{{ owncloud_docker_ports }}:3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{ owncloud_docker_env_root_password }}"
      MYSQL_DATABASE: "{{ owncloud_docker_env_database }}"
      MYSQL_USER: "{{ owncloud_docker_env_user }}"
      MYSQL_PASSWORD: "{{ owncloud_docker_env_password }}"
  tags:
    - install-owncloud

# CloudBoz - owncloud Firewall Install
- name: "'{{ ufw_rule }}' port '{{ owncloud_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ owncloud_docker_ports | quote }}"
  tags:
    - install-owncloud

# CloudBoz - owncloud Uninstall
- name: "uninstall owncloud"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ owncloud_docker_name }}"
    state: absent
  tags:
    - uninstall-owncloud

# CloudBoz - owncloud Firewall Uninstall
- name: "'{{ ufw_rule }}' port '{{ owncloud_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
    delete: yes
  loop:
    - "{{ owncloud_docker_ports | quote }}"
  tags:
    - uninstall-owncloud

# CloudBoz - owncloud Uninstall with Data
- name: "uninstall owncloud data"
  become_user: "{{ ansible_user }}"
  shell: "sudo rm -fr /cloudboz/{{ owncloud_docker_name }}-data"
  tags:
    - uninstall-owncloud-data