# ANSIBLE ENV
ansible_connection: ssh
ansible_user: dhani-azure
ansible_ssh_pass: 
ansible_sudo_pass: 
ansible_ssh_private_key_file: files/secrets/dhani-azure.pem
ansible_python_interpreter: /usr/bin/python3

# SSH ENV
# pass_auth: PasswordAuthentication yes
# pubkey_auth: PubkeyAuthentication yes

# SWAP ENV
# swap_file_path: /swapfile
# swap_file_size: 2048
# swappiness: 1

# DOCKER ENV
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg


