# CloudBoz - Mongo Express Install
- name: "install mongoexpress"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ mongoexpress_docker_name }}"
    image: "{{ mongoexpress_docker_image }}:{{ mongoexpress_docker_tag }}"
    networks:
      - name: cloudboz-network
    restart_policy: always
    env:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "{{ mongodb_docker_env_root_username }}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "{{ mongodb_docker_env_root_password }}"
      ME_CONFIG_MONGODB_URL: "mongodb://{{mongodb_docker_env_root_username}}:{{mongodb_docker_env_root_password}}@{{ mongodb_docker_name }}:{{ mongodb_docker_ports | quote }}"
    ports:
      - "{{ mongoexpress_docker_ports }}:8081"
  tags:
    - install-mongoexpress

# CloudBoz - Mongo Express Uninstall
- name: "Remove mongoexpress"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ mongoexpress_docker_name }}"
    state: absent
  tags:
    - uninstall-mongoexpress
