# CloudBoz - PGAdmin Install
- name: "Install PGAdmin"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ pgadmin_docker_name }}"
    image: "{{ pgadmin_docker_image }}:{{ pgadmin_docker_tag }}"
    networks:
      - name: cloudboz-network
    restart_policy: always
    ports:
      - "{{ pgadmin_docker_ports }}:80"
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ pgadmin_docker_env_default_email }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ pgadmin_docker_env_default_password }}"
  tags:
    - install-pgadmin
  
# CloudBoz - PGAdmin Uninstall
- name: "Remove PGAdmin"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ pgadmin_docker_name }}"
    state: absent
  tags:
    - uninstall-pgadmin
