# CloudBoz - GitLab Install
- name: "Install gitlab"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ gitlab_docker_name }}"
    image: "{{ gitlab_docker_image }}:{{ gitlab_docker_tag }}"
    networks:
      - name: cloudboz-network
    volumes:
      - "/cloudboz/{{ gitlab_docker_name }}-data/config:/etc/gitlab"
      - "/cloudboz/{{ gitlab_docker_name }}-data/logs:/var/log/gitlab"
      - "/cloudboz/{{ gitlab_docker_name }}-data/data:/var/opt/gitlab"
    restart_policy: always
    ports:
      - "{{ gitlab_docker_ports_http }}:80"
      - "{{ gitlab_docker_ports_https }}:443"
      - "{{ gitlab_docker_ports_ssh }}:22"
    env:
      GITLAB_OMNIBUS_CONFIG: "gitlab_rails['initial_root_password'] = '{{ gitlab_docker_env_password }}'"
    shm_size: '256m'
  tags:
    - install-gitlab

# CloudBoz - GitLab Uninstall
- name: "Remove gitlab"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ gitlab_docker_name }}"
    state: absent
  tags:
    - uninstall-gitlab

# CloudBoz - GitLab Uninstall with Data
- name: "uninstall gitlab data"
  become_user: "{{ ansible_user }}"
  shell: "sudo rm -fr /cloudboz/{{ gitlab_docker_name }}-data"
  tags:
    - uninstall-gitlab-data