# CloudBoz - PhpMyAdmin Install
- name: "install phpmyadmin"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ phpmyadmin_docker_name }}"
    image: "{{ phpmyadmin_docker_image }}:{{ phpmyadmin_docker_tag }}"
    networks:
      - name: cloudboz-network
    restart_policy: always
    env:
      PMA_HOST: "{{ mysql_docker_name }}"
      PMA_PORT: "{{ mysql_docker_ports | quote }}"
      PMA_USER: "root"
      PMA_PASSWORD: "{{ mysql_docker_env_root_password }}"
    ports:
      - "{{ phpmyadmin_docker_ports }}:80"
  tags:
    - install-phpmyadmin

# CloudBoz - phpmyadmin Uninstall
- name: "Remove phpmyadmin"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ phpmyadmin_docker_name }}"
    state: absent
  tags:
    - uninstall-phpmyadmin
