# CloudBoz - Jenkins Install
- name: "install jenkins"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ jenkins_docker_name }}"
    image: "{{ jenkins_docker_image }}:{{ jenkins_docker_tag}}"
    ports:
      - "{{ jenkins_docker_ui_ports }}:8080"
      - "{{ jenkins_docker_slave_ports}}:50000"
    volumes:
      - "/cloudboz/{{ jenkins_docker_name }}-data:/var/jenkins_home"
    restart_policy: always
    env:
      USER_UID: "1000"
      USER_GID: "1000"
    networks:
      - name: cloudboz-network
  tags:
      - install-jenkins

# CloudBoz - Jenkins Install
# - name: "change permission"
#   become_user: "{{ ansible_user }}"
#   shell: "sudo chown -R 1000:1000 /cloudboz/{{ jenkins_docker_name }}-data"
#   tags:
#     - install-jenkins

# CloudBoz - Jenkins Uninstall
- name: "uninstall jenkins"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ jenkins_docker_name }}"
    state: absent
  tags:
    - uninstall-jenkins

# CloudBoz - Jenkins Uninstall with Data
- name: "uninstall jenkins data"
  become_user: "{{ ansible_user }}"
  shell: "sudo rm -fr /cloudboz/{{ jenkins_docker_name }}-data"
  tags:
    - uninstall-jenkins-data