# CloudBoz - kubernetes Install
- name: "install kubernetes"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ kubernetes_docker_name }}"
    image: "{{ kubernetes_docker_image }}:{{ kubernetes_docker_tag }}"
    networks:
      - name: cloudboz-network
    volumes:
      - "/cloudboz/{{ kubernetes_docker_name }}-data:/var/lib/kubernetes"
    restart_policy: always
    ports:
      - "{{ kubernetes_docker_http_ports }}:80"
      - "{{ kubernetes_docker_https_ports }}:443"
    privileged: true
  tags:
    - install-kubernetes

# CloudBoz - kubernetes Uninstall
- name: "uninstall kubernetes"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ kubernetes_docker_name }}"
    state: absent
  tags:
    - uninstall-kubernetes

# CloudBoz - kubernetes Uninstall with Data
- name: "uninstall kubernetes data"
  become_user: "{{ ansible_user }}"
  shell: "sudo rm -fr /cloudboz/{{ kubernetes_docker_name }}-data"
  tags:
    - uninstall-kubernetes-data