# CloudBoz - Kafka Install
- name: "install kafka"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ kafka_docker_name }}"
    image: "{{ kafka_docker_image }}:{{ kafka_docker_tag }}"
    networks:
      - name: cloudboz-network
    volumes:
      - "/cloudboz/{{ kafka_docker_name }}-data:/var/lib/kafka"
    restart_policy: always
    ports:
      - "{{ kafka_docker_ports }}:3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{ kafka_docker_env_root_password }}"
      MYSQL_DATABASE: "{{ kafka_docker_env_database }}"
      MYSQL_USER: "{{ kafka_docker_env_user }}"
      MYSQL_PASSWORD: "{{ kafka_docker_env_password }}"
  tags:
    - install-kafka

# CloudBoz - Kafka Firewall Install
- name: "'{{ ufw_rule }}' port '{{ kafka_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ kafka_docker_ports | quote }}"
  tags:
    - install-kafka

# CloudBoz - Kafka Uninstall
- name: "uninstall kafka"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ kafka_docker_name }}"
    state: absent
  tags:
    - uninstall-kafka

# CloudBoz - Kafka Firewall Uninstall
- name: "'{{ ufw_rule }}' port '{{ kafka_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
    delete: yes
  loop:
    - "{{ kafka_docker_ports | quote }}"
  tags:
    - uninstall-kafka

# CloudBoz - Kafka Uninstall with Data
- name: "uninstall kafka data"
  become_user: "{{ ansible_user }}"
  shell: "sudo rm -fr /cloudboz/{{ kafka_docker_name }}-data"
  tags:
    - uninstall-kafka-data